-n 

2025-04-22-11.12.19.551023+480 I5E325               LEVEL: Error
PID     : 5424                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.12.46.263645+480 I331E325             LEVEL: Error
PID     : 5531                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.13.09.317685+480 I657E325             LEVEL: Error
PID     : 5635                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.14.40.050728+480 I983E325             LEVEL: Error
PID     : 6373                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.14.43.231172+480 I1309E325            LEVEL: Error
PID     : 6373                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.14.59.947667+480 I1635E325            LEVEL: Error
PID     : 6460                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.15.02.972047+480 I1961E325            LEVEL: Error
PID     : 6475                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.15.19.149693+480 I2287E325            LEVEL: Error
PID     : 6475                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.18.54.912449+480 I2613E325            LEVEL: Error
PID     : 7104                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.18.54.923891+480 I2939E325            LEVEL: Error
PID     : 7104                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.18.57.780121+480 I3265E325            LEVEL: Error
PID     : 7104                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.24.49.395013+480 I3591E325            LEVEL: Error
PID     : 8098                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.24.49.409590+480 I3917E325            LEVEL: Error
PID     : 8098                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.24.57.689885+480 I4243E325            LEVEL: Error
PID     : 8126                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.24.57.699220+480 I4569E325            LEVEL: Error
PID     : 8126                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.25.01.491977+480 I4895E325            LEVEL: Error
PID     : 8126                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.26.14.101755+480 I5221E325            LEVEL: Error
PID     : 8351                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.26.14.110365+480 I5547E325            LEVEL: Error
PID     : 8351                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.26.28.818301+480 I5873E325            LEVEL: Error
PID     : 8351                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.27.32.148782+480 I6199E325            LEVEL: Error
PID     : 8972                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.27.32.158298+480 I6525E325            LEVEL: Error
PID     : 8972                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.27.37.464370+480 I6851E325            LEVEL: Error
PID     : 9001                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.27.37.496029+480 I7177E325            LEVEL: Error
PID     : 9001                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.29.35.901683+480 I7503E325            LEVEL: Error
PID     : 9383                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.29.35.916322+480 I7829E325            LEVEL: Error
PID     : 9383                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.30.06.877614+480 I8155E325            LEVEL: Error
PID     : 9497                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.30.06.889974+480 I8481E325            LEVEL: Error
PID     : 9497                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.30.09.900036+480 I8807E325            LEVEL: Error
PID     : 9497                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:110
MESSAGE : DIA3202C The TCP/IP call "connect" returned an errno="61".

2025-04-22-11.33.19.931004+480 I9133E379            LEVEL: Error
PID     : 9920                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "db2-mcp" was not found, TCP/IP function 
          "getaddrinfo" error return code = "8".

2025-04-22-11.33.19.933027+480 I9513E3732           LEVEL: Severe
PID     : 9920                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x000000010801EF44 _Z16sqljcLogCCIErrorP10sqljCmnMgrPKcP12SQLCC_COND_Thllll + 0x1A8
  [1] 0x000000010801FA8C _Z16sqljcCommConnectP10sqljCmnMgr + 0x354
  [2] 0x000000010801F054 _Z15sqljcCmnMgrInitP10sqljCmnMgrP17SQLCC_COMHANDLE_TPhmP14db2UCconHandleh24sqljcInvokeCommExitStatePP21sqljcCommexitCommInfoP8s + 0xB4
  [3] 0x000000010828ABB8 _Z20sqljrCreateTransportP14db2UCconHandle + 0x144
  [4] 0x0000000107BF9870 _Z23sqljrAssociateTransportP14db2UCconHandlePlbP19SQLE_SRVLST_DBENTRYPi + 0x90
  [5] 0x000000010828A2F4 _Z26sqljrConnectBasedOnCatalogP14db2UCconHandlePibPb + 0x2A0
  [6] 0x000000010828909C _Z20sqljrInternalConnectP14db2UCconHandlePbPib + 0x48C
  [7] 0x000000010828A9E8 _Z30sqljrFindBestAddressAndConnectP14db2UCconHandle + 0x70
  [8] 0x00000001082663F4 _Z23sqljrDrdaArAuthenticateP14db2UCinterfacelPj + 0x1EC
  [9] 0x000000010821F384 _Z20sqlexAppAuthenticateP14db2UCinterface + 0xA10
  [10] 0x000000010828AD04 _Z18sqljrDrdaArConnectP14db2UCinterface + 0xC0
  [11] 0x0000000108232040 _Z16sqleUCdrdaARinitP14db2UCconHandle + 0xE8
  [12] 0x00000001083A34FC sqleUCappConnect + 0xA8C
  [13] 0x0000000107C10C28 _Z14CLI_sqlConnectP15CLI_CONNECTINFOP5sqlcaP19CLI_ERRORHEADERINFO + 0x1CA4
  [14] 0x0000000107C8BB90 _Z11SQLConnect2P15CLI_CONNECTINFOPhsS1_sS1_sS1_sh + 0x1320
  [15] 0x0000000107C88774 _Z17SQLDriverConnect2P15CLI_CONNECTINFOPvPhsS2_sPsthhP19CLI_ERRORHEADERINFO + 0xBFD4
  [16] 0x0000000107D4209C SQLDriverConnectW + 0x8AC
  [17] 0x000000010500F464 _python_ibm_db_connect_helper + 0x10E4
  [18] 0x0000000105CA46A4 cfunction_call + 0x3C
  [19] 0x0000000105C3FCB0 _PyObject_MakeTpCall + 0x80
  [20] 0x0000000105D67604 _PyEval_EvalFrameDefault + 0xD154
  [21] 0x0000000105D6CCFC _PyEval_Vector + 0x9C
  [22] 0x0000000105C40AD8 _PyVectorcall_Call + 0xA0
  [23] 0x0000000105D69E58 _PyEval_EvalFrameDefault + 0xF9A8
  [24] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [25] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [26] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [27] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [28] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [29] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [30] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [31] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [32] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [33] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [34] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [35] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [36] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [37] 0x00000001052C84E0 task_step_impl + 0x1B8
  [38] 0x00000001052C82B4 task_step + 0x34
  [39] 0x0000000105C3FCB0 _PyObject_MakeTpCall + 0x80
  [40] 0x0000000105D9726C context_run + 0xD4
  [41] 0x0000000105CA50B4 cfunction_vectorcall_FASTCALL_KEYWORDS + 0x50
  [42] 0x0000000105D69E58 _PyEval_EvalFrameDefault + 0xF9A8
  [43] 0x0000000105D591FC PyEval_EvalCode + 0x114
  [44] 0x0000000105DD6F6C pyrun_file + 0xF0
  [45] 0x0000000105DD673C _PyRun_SimpleFileObject + 0x120
  [46] 0x0000000105DD5CBC _PyRun_AnyFileObject + 0xE8
  [47] 0x0000000105DFF54C pymain_run_file_obj + 0xDC
  [48] 0x0000000105DFED30 pymain_run_file + 0x48
  [49] 0x0000000105DFE544 Py_RunMain + 0x724

2025-04-22-11.34.24.747836+480 I13246E379           LEVEL: Error
PID     : 9920                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "db2-mcp" was not found, TCP/IP function 
          "getaddrinfo" error return code = "8".

2025-04-22-11.34.24.749977+480 I13626E3732          LEVEL: Severe
PID     : 9920                 TID : 8594770944     PROC : Python
INSTANCE: DB2                  NODE : 000
HOSTNAME: macair
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x000000010801EF44 _Z16sqljcLogCCIErrorP10sqljCmnMgrPKcP12SQLCC_COND_Thllll + 0x1A8
  [1] 0x000000010801FA8C _Z16sqljcCommConnectP10sqljCmnMgr + 0x354
  [2] 0x000000010801F054 _Z15sqljcCmnMgrInitP10sqljCmnMgrP17SQLCC_COMHANDLE_TPhmP14db2UCconHandleh24sqljcInvokeCommExitStatePP21sqljcCommexitCommInfoP8s + 0xB4
  [3] 0x000000010828ABB8 _Z20sqljrCreateTransportP14db2UCconHandle + 0x144
  [4] 0x0000000107BF9870 _Z23sqljrAssociateTransportP14db2UCconHandlePlbP19SQLE_SRVLST_DBENTRYPi + 0x90
  [5] 0x000000010828A2F4 _Z26sqljrConnectBasedOnCatalogP14db2UCconHandlePibPb + 0x2A0
  [6] 0x000000010828909C _Z20sqljrInternalConnectP14db2UCconHandlePbPib + 0x48C
  [7] 0x000000010828A9E8 _Z30sqljrFindBestAddressAndConnectP14db2UCconHandle + 0x70
  [8] 0x00000001082663F4 _Z23sqljrDrdaArAuthenticateP14db2UCinterfacelPj + 0x1EC
  [9] 0x000000010821F384 _Z20sqlexAppAuthenticateP14db2UCinterface + 0xA10
  [10] 0x000000010828AD04 _Z18sqljrDrdaArConnectP14db2UCinterface + 0xC0
  [11] 0x0000000108232040 _Z16sqleUCdrdaARinitP14db2UCconHandle + 0xE8
  [12] 0x00000001083A34FC sqleUCappConnect + 0xA8C
  [13] 0x0000000107C10C28 _Z14CLI_sqlConnectP15CLI_CONNECTINFOP5sqlcaP19CLI_ERRORHEADERINFO + 0x1CA4
  [14] 0x0000000107C8BB90 _Z11SQLConnect2P15CLI_CONNECTINFOPhsS1_sS1_sS1_sh + 0x1320
  [15] 0x0000000107C88774 _Z17SQLDriverConnect2P15CLI_CONNECTINFOPvPhsS2_sPsthhP19CLI_ERRORHEADERINFO + 0xBFD4
  [16] 0x0000000107D4209C SQLDriverConnectW + 0x8AC
  [17] 0x000000010500F464 _python_ibm_db_connect_helper + 0x10E4
  [18] 0x0000000105CA46A4 cfunction_call + 0x3C
  [19] 0x0000000105C3FCB0 _PyObject_MakeTpCall + 0x80
  [20] 0x0000000105D67604 _PyEval_EvalFrameDefault + 0xD154
  [21] 0x0000000105D6CCFC _PyEval_Vector + 0x9C
  [22] 0x0000000105C40AD8 _PyVectorcall_Call + 0xA0
  [23] 0x0000000105D69E58 _PyEval_EvalFrameDefault + 0xF9A8
  [24] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [25] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [26] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [27] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [28] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [29] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [30] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [31] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [32] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [33] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [34] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [35] 0x0000000105D5DFEC _PyEval_EvalFrameDefault + 0x3B3C
  [36] 0x0000000105C5E720 gen_send_ex2 + 0xCC
  [37] 0x00000001052C84E0 task_step_impl + 0x1B8
  [38] 0x00000001052C82B4 task_step + 0x34
  [39] 0x0000000105C3FCB0 _PyObject_MakeTpCall + 0x80
  [40] 0x0000000105D9726C context_run + 0xD4
  [41] 0x0000000105CA50B4 cfunction_vectorcall_FASTCALL_KEYWORDS + 0x50
  [42] 0x0000000105D69E58 _PyEval_EvalFrameDefault + 0xF9A8
  [43] 0x0000000105D591FC PyEval_EvalCode + 0x114
  [44] 0x0000000105DD6F6C pyrun_file + 0xF0
  [45] 0x0000000105DD673C _PyRun_SimpleFileObject + 0x120
  [46] 0x0000000105DD5CBC _PyRun_AnyFileObject + 0xE8
  [47] 0x0000000105DFF54C pymain_run_file_obj + 0xDC
  [48] 0x0000000105DFED30 pymain_run_file + 0x48
  [49] 0x0000000105DFE544 Py_RunMain + 0x724
